### ISSUE TITLE
SAM docker build fails due to API change in onnxruntime

### ISSUE THREAD

**Issue by jpodivin** [HumanSignal/label-studio-ml-backend#353]
It seems that the API has changed, and since the library isn't pinned the change now breaks the build.

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Removing intermediate container f9783fc2e7d5
 ---> 01a57950f1a4
Step 9/12 : COPY . ./
 ---> ccb082b64d72
Step 10/12 : RUN python3 onnxconverter.py
 ---> Running in 11efd499e8b9
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "onnxconverter.py", line 67, in <module>
    convert(VITH_CHECKPOINT)
  File "onnxconverter.py", line 58, in convert
    quantize_dynamic(
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'
```

**Comment by jpodivin** [comment]
The change was introduced in https://github.com/microsoft/onnxruntime/pull/16422

**Comment by Buckler89** [comment]
@shondle any idea?

**Comment by shondle** [comment]
I haven't checked, but what jpodivin does with pinning the dependency should work.

**Comment by shondle** [comment]
> I haven't checked, but what jpodivin does with pinning the dependency should work.

All checks passed, and jpodivin's PR has been merged. Can you check if it works now?
